logging:
  level:
    org:
      springframework:
        web: INFO
server:
  port: 8001

spring:
  application:
    name: starball-springboot-service-order-api-impl
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      ##register current service into eureka domain
      defaultZone: http://localhost:8100/eureka/
    ##register service
    register-with-eureka: true
    ##search service
    fetch-registry: true
