##default eureka port:8761
server:
  port: 8100
##服务端关闭鉴权代码
security:
  basic:
    enabled: false
logging:
  level:
    org:
      springframework:
        web: INFO
eureka:

  instance:
    hostname: 127.0.0.1
    #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    ##因为自己是注册中心，所以不需要将自己注册给自己的注册中心（集群时候需要将自己设为true）
    register-with-eureka: false
    fetch-registry: false
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: starball-eureka-server