logging:
  level:
    org:
      springframework:
        web: INFO
server:
  port: 8200

spring:
  application:
    name: starball-springboot-admin
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: ming
      password: 110110