logging:
  level:
    org:
      springframework:
        web: INFO
server:
  port: 8001

spring:
  application:
    name: starball-springboot-service-order-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
#  redis:
#    database: 2
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    pool:
#    max-active: 20

  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: ming
      password: 110110

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: {spring.security.user.password}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      ##register current service into eureka domain
      defaultZone: http://localhost:8100/eureka/
    ##register service
    register-with-eureka: true
    ##search service
    fetch-registry: true
